<a href="https://colab.research.google.com/github/trancenoid/RNNs/blob/master/Copytam_Da_RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import io
text = io.open('lyrics.txt').read().lower()

def prep_XY(text, Tx = 40, stride = 3):
  X = []
  Y = []
  for i in range(0,len(text) - Tx, stride):
      X.append(text[i : i + Tx])
      Y.append(text[i + Tx])
  return X,Y

X,Y = prep_XY(text, 40, 3)

In [19]:
print(X[1], Y[1])

htool jigar
 ya baba 
qaatil hai nazar
  y


In [50]:
chars = sorted(list(set(text)))
idx_char = dict(enumerate(chars))
char_idx = dict((c,i) for i,c in enumerate(chars))
len(char_idx)

29

In [0]:
import numpy as np

def vectorize(X,Y, char_idx, Tx = 40):
  x = np.zeros((len(X), Tx, len(char_idx)))
  y = np.zeros((len(X), len(char_idx)))
  for i,sx in enumerate(X):
    for j,c in enumerate(sx):
      x[i, j, char_idx[c]] = 1
    y[i, char_idx[Y[i]]] = 1
  return x,y

x,y = vectorize(X,Y, char_idx, 40)

In [55]:
print(x)

[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 1.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [0. 1. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 1. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 1. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 1. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 1. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  ...
  [0. 1. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 1. 0. ... 0. 0. 0.]]]
